// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about: defineAsyncComponent(() => import("./About/index.vue")),
  footer: defineAsyncComponent(() => import("./Footer/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  history: defineAsyncComponent(() => import("./History/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  navigation: defineAsyncComponent(() => import("./Navigation/index.vue")),
  social: defineAsyncComponent(() => import("./Social/index.vue")),
  title: defineAsyncComponent(() => import("./Title/index.vue")),
  works: defineAsyncComponent(() => import("./Works/index.vue")),
});
